- name: Demo on Vars
  hosts: all
  
  vars:
   URL: play.example.com
   PROJECT: exammple
  vars_prompt:
    - name: URL
      prompt: Enter URL
      private: no
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
    - name: Print URL from Task
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: task.example.com