- name: Demo on Vars
  hosts: all
#  vars_files:
#    - example-vars.yml
#  vars:
#    URL: play.example.com
#    PROJECT: exammple
#  vars_prompt:
#    - name: URL
#      prompt: Enter URL
#      private: no
  tasks:
    - name: Print URL
      debug:
        msg: URL = {{ URL }}
    - name: Print URL from Task
      debug:
        msg: URL = {{ URL }}
      vars:
        URL: task.example.com

# Variable Precedence
# command line vars with -e
# Tasks
# vars_files
# vars_prompt
# vars
# inventory vars

- name: Demo on Dynamic Vars
  hosts: NEW
  tasks:

    - name: Gather date
      shell: date +%F
      register: out

    - name: Print Date
      debug:
        msg: Date = {{ out.stdout }}

    - name: Set a fact
      set_fact:
        DATE: "{{ out.stdout }}"

    - name: Print DATE
      debug:
        msg: DATE = {{ DATE }}


- name: Print some facts
  hosts: all
  tasks:
    - name: Print facts
      debug:
        msg: Hostname = {{ ansible_hostname }}
