- name: Setup HostName
  shell: set-hostname {{COMPONENT}}

- name: Update Rsyslog config
  copy:
    src: rsyslog.conf
    dest: /etc/rsyslog.d/todo.conf

- name: Restart rsyslog
  systemd:
    name: rsyslog
    state: restarted